### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by itsmeru**
我是劉晏儒，http://54.238.163.121:8000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. /api/mrts should not contain duplicate mrt names.
2. nextPage field of the last page should be null. For example, nextPage of http://54.238.163.121:8000/api/attractions?page=4 should be null.
3. http://54.238.163.121:8000/api/attractions?page=4&keyword=%E5%8A%8D%E6%BD%AD should get some attraction data around 劍潭 mrt station.

**Comment by itsmeru** [comment]
修改完成，請彭彭確認

**Review by cwpeng — CHANGES_REQUESTED** [review]
Sorry for that.

http://54.238.163.121:8000/api/attractions?page=0&keyword=%E5%8A%8D%E6%BD%AD should get some data, but http://54.238.163.121:8000/api/attractions?page=4&keyword=%E5%8A%8D%E6%BD%AD should not.

**Comment by itsmeru** [comment]
修正完成～麻煩確認

**Review by cwpeng — CHANGES_REQUESTED** [review]
Just as http://54.238.163.121:8000/api/attractions?page=4 , nextPage field of http://54.238.163.121:8000/api/attractions?page=0&keyword=%E5%8A%8D%E6%BD%AD should be null as well.

**Comment by itsmeru** [comment]
修正完成

**Comment by cwpeng** [comment]
nextPage of http://54.238.163.121:8000/api/attractions?page=0&keyword=%E5%8C%97 should not be null. Generally speaking, nextPage field of the last page should be null.

**Comment by itsmeru** [comment]
請彭彭確認

**Review by cwpeng — CHANGES_REQUESTED** [review]
You should not use id range to do pagination. id is not guaranteed to be continuous number.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
