### PR TITLE
Part 5

### PR DESCRIPTION
**Pull request by itsmeru**
http://54.168.41.128:8000/

彭彭午安，我是晏儒，作業麻煩您確認！辛苦了！

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Request and response format of Booking API should align with API specs.

**Comment by itsmeru** [comment]
修正完成，請彭彭確認

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your booking page calls User Auth API 3 times after page load. Only 1 time User Auth API call can handle all requirements.

**Comment by itsmeru** [comment]
修正完成，請彭彭確認

**Review by cwpeng — CHANGES_REQUESTED** [review]
In the booking page, you call User Auth API 2 times.

**Comment by itsmeru** [comment]
修正完成，請確認～辛苦了

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
